dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: oskari
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
