dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "oskari"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
